# Generated by Django 6.1.1 on 2026-09-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('product_type', models.CharField(choices=[('RANK', 'Привилегия'), ('CURRENCY', 'Донат-валюта')], default='RANK', max_length=20, verbose_name='Тип товара')),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена, zł')),
                ('price_per_unit', models.DecimalField(decimal_places=4, default=0.1, max_digits=10, verbose_name='Цена за 1 монету, zł')),
                ('min_quantity', models.PositiveIntegerField(default=10, verbose_name='Минимум')),
                ('max_quantity', models.PositiveIntegerField(default=10000, verbose_name='Максимум')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Своя картинка')),
                ('image_url', models.CharField(blank=True, max_length=255, verbose_name='Путь к картинке')),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='Бейдж')),
                ('accent', models.CharField(default='#ff3040', max_length=20, verbose_name='Цвет')),
                ('commands', models.TextField(help_text='Одна команда на строку. {player} — ник, {quantity} — количество.', verbose_name='Команды выдачи')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('featured', models.BooleanField(default=False, verbose_name='Популярный')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=16, verbose_name='Игрок')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает оплаты'), ('PAID', 'Оплачен'), ('DELIVERED', 'Выдан'), ('FAILED', 'Ошибка выдачи'), ('CANCELED', 'Отменён')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=120, verbose_name='ID оплаты')),
                ('rcon_log', models.TextField(blank=True, verbose_name='RCON лог')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Выдан')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
